src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Vegetables</fullName>
                </value>
                <value>
                    <fullName>Steel</fullName>
                </value>
                <value>
                    <fullName>Lumber</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product_c</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductController.cls
public with sharing class ProductController {
	@AuraEnabled(cacheable=true)
	public static List<Product__c> getProducts(String type, String family, String searchTerm) {

		String query = 'SELECT Id, Name, Description__c FROM Product__c WHERE Name != NULL';

		if (type != null && type != '') {
			query += ' AND Type__c = :type';
		}
		if (family != null && family != '') {
			query += ' AND Family__c = :family';
		}
		if (searchTerm != null && searchTerm != '') {
			String searchValue = '%' + searchTerm + '%';
			query += ' AND (Name LIKE :searchValue OR Description__c LIKE :searchValue)';
		}

		return Database.query(query);
	}
}